Webadvert_Web/Models/Accounts/ConfirmModel.cs
using System.ComponentModel.DataAnnotations;

namespace Webadvert_Web.Models.Accounts
{
    public class ConfirmModel
    {
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Code is required.")]
        public string Code { get; set; }
    }
}

Webadvert_Web/Models/Accounts/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace Webadvert_Web.Models.Accounts
{
    public class LoginModel
    {
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Password is required.")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }
    }
}

Webadvert_Web/Models/Accounts/ResetPassword.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Webadvert_Web.Models.Accounts
{
    public class ResetPassword { 

        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class ConfirmPasswordReset
    {
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(6, ErrorMessage = "Password must be at least 6 characters long")]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Passwrod and its confirmation does not match")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Token is required.")]
        [Display(Name = "Token")]
        public string ResetToken { get; set; }
    }
}

Webadvert_Web/Models/Accounts/SignupModel.cs
using System.ComponentModel.DataAnnotations;

namespace Webadvert_Web.Models.Accounts
{
    public class SignupModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [StringLength(6, ErrorMessage ="Password must be at least 6 characters long")]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Passwrod and its confirmation does not match")]
        public string ConfirmPassword { get; set; }
    }
}

Webadvert_Web/Controllers/AccountsController.cs
using Amazon.AspNetCore.Identity.Cognito;
using Amazon.Extensions.CognitoAuthentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Webadvert_Web.Models.Accounts;

namespace Webadvert_Web.Controllers
{
    public class AccountsController : Controller
    {
        private readonly SignInManager<CognitoUser> _signInManager;
        private readonly ILogger<AccountsController> _logger;
        private readonly UserManager<CognitoUser> _userManager;
        private readonly CognitoUserPool _cognitorUserPool;
        public AccountsController(SignInManager<CognitoUser> signInManager,
            UserManager<CognitoUser> userManager,
            CognitoUserPool pool,
            ILogger<AccountsController> logger)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _cognitorUserPool = pool;
            _logger = logger;
        }
        public async Task<IActionResult> Signup()
        {
            var model = new SignupModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Signup(SignupModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _cognitorUserPool.GetUser(model.Email);

                if (user.Status != null)
                {
                    ModelState.AddModelError("UserExists", "User with this email already exists");
                    return View(model);
                }

                user.Attributes.Add(CognitoAttribute.Name.ToString(), model.Email);

                var createdUser = await _userManager.CreateAsync(user, password: model.Password);

                if (createdUser.Succeeded)
                {
                    RedirectToAction("Confirm");
                }
            }
            return View();
        }

        public async Task<IActionResult> Confirm(ConfirmModel model)
        {
            return View(model);
        }

        [HttpPost]
        [ActionName("Confirm")]
        public async Task<IActionResult> Confirm_Post(ConfirmModel model)
        {
            if(ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);

                if (user == null)
                {
                    ModelState.AddModelError("NotFound", "A user with the given email address was not found");
                    return View(model);
                }

                var result = await (_userManager as CognitoUserManager<CognitoUser>).ConfirmSignUpAsync(user, model.Code, true).ConfigureAwait(false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach(var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }

                    return View(model);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Login(LoginModel model)
        {
            return View(model);
        }

        [HttpPost]
        [ActionName("Login")]
        public async Task<IActionResult> Login_Post(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                } else
                {
                    ModelState.AddModelError("LoginError", "Email and password does not match");

                    return View(model);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ResetPassword(ResetPassword model)
        {
            return View(model);
        }

        [HttpPost]
        [ActionName("ResetPassword")]
        public async Task<IActionResult> ResetPassword_Post(ResetPassword model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);

                if (user == null)
                {
                    ModelState.AddModelError("NotFound", "A user with the given email address was not found");
                    return View(model);
                }

                var result = await (_userManager as CognitoUserManager<CognitoUser>).ResetPasswordAsync(user).ConfigureAwait(false);
                if (result.Succeeded)
                {
                    return RedirectToAction("ConfirmPasswordReset");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }

                    return View(model);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmPasswordReset(ConfirmPasswordReset model)
        {
            return View(model);
        }

        [HttpPost]
        [ActionName("ConfirmPasswordReset")]
        public async Task<IActionResult> ConfirmPasswordReset_Post(ConfirmPasswordReset model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);

                if (user == null)
                {
                    ModelState.AddModelError("NotFound", "A user with the given email address was not found");
                    return View(model);
                }

                var result = await (_userManager as CognitoUserManager<CognitoUser>).ResetPasswordAsync(user, model.ResetToken, model.Password).ConfigureAwait(false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }

                    return View(model);
                }
            }

            return View(model);
        }
    }
}

Webadvert_Web/Views/Accounts/Confirm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Webadvert_Web.Models.Accounts.ConfirmModel

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="Accounts" asp-action="Confirm">
            <div asp-validation-summary="All" class="text-danger">
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Code"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-secondary">Confirm</button>
        </form>
    </div>
</div>

Webadvert_Web/Views/Accounts/ConfirmPasswordReset.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


@model Webadvert_Web.Models.Accounts.ConfirmPasswordReset

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="Accounts" asp-action="ConfirmPasswordReset">
            <h4>Create a new Account</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger">
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-secondary">Signup</button>
        </form>
    </div>
</div>

Webadvert_Web/Views/Accounts/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Webadvert_Web.Models.Accounts.LoginModel

<div class="row">
    <div class="col-md-4">
        <h4>Login usring your email address and password</h4>
        <h5>
            <a asp-controller="Accounts" asp-action="Signup">
                If you are not a member you can sign up here
            </a>
        </h5>

        <form method="post" asp-controller="Accounts" asp-action="Login">
            <h4>Create a new Account</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger">
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label asp-for="RememberMe"></label>
                    <input type="checkbox" asp-for="RememberMe" class="form-control" />
                    @*@Html.DisplayName("Remember Me")*@
                    @*<span asp-validation-for="RememberMe" class="text-danger"></span>*@
                </div>
            </div>

            <button type="submit" class="btn btn-secondary">Login</button>

            <br />
            <h5>
                <a asp-controller="Accounts" asp-action="ResetPassword">
                    Click To Reset Your Password
                </a>
            </h5>
        </form>
    </div>
</div>

Webadvert_Web/Views/Accounts/ResetPassword.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Webadvert_Web.Models.Accounts.ResetPassword

<div class="row">
    <div class="col-md-4">
        <h4>Reset Your Password</h4>
        <h5>
            <a asp-controller="Accounts" asp-action="ResetPassword">
                If you are not a member you can sign up here
            </a>
        </h5>

        <form method="post" asp-controller="Accounts" asp-action="ResetPassword">
            <h4>Password Reset</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-secondary">Reset</button>
        </form>
    </div>
</div>

Webadvert_Web/Views/Accounts/Signup.cshtml
@{
    ViewData["Title"] = "View";
}

@model Webadvert_Web.Models.Accounts.SignupModel;

<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="Accounts" asp-action="Signup">
            <h4>Create a new Account</h4>
            <hr />
            <div asp-validation-summary="All" class="text-danger">
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-secondary">Signup</button>
        </form>
    </div>
</div>